### ISSUE TITLE
Screenshot, please?

### ISSUE THREAD

**Issue by erikb85** [BohdanTkachenko/xunit-reports-viewer#5]
Hi,

I'm deciding for a xunit reports viewer and your tool is number one on Google. But because I don't even know yet what npm is I'd like to see how the end result looks before investigating further if that's the right tool for me. Could you add a screenshot to the readme? It's a GUI tool, right?

**Comment by BohdanTkachenko** [comment]
Here they are. I'll update README later, so it will have screenshots.

![screen shot 2015-05-18 at 1 49 50 pm](https://cloud.githubusercontent.com/assets/929598/7679384/d2504d7e-fd64-11e4-9ad2-0c9add5aa7d5.png)
![screen shot 2015-05-18 at 1 49 39 pm](https://cloud.githubusercontent.com/assets/929598/7679387/d6a5fe14-fd64-11e4-9142-71bd15479b66.png)

**Comment by erikb85** [comment]
Cheers! You'll hear from me if we decide to use it. :)
